sudo: required

language: python

install:
  - pip install -r requirements.txt

services:
- docker

before_install:
    - docker build -t martincleven/awsimage -f Dockerfile .

script:
    - docker run -e CI=true martincleven/awsimage pytest ./tests

#deploy:
#    provider: elasticbeanstalk
#    region: "eu-central-1"
#    app: "docker-react"
#    env: "DockerReact-env"
#    bucket_name: "elasticbeanstalk-eu-central-1-657167693396"
#    bucket_path: "docker-react"
#    on:
#        branch: master
#
#    # AWS Keys
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key:
#        secure: $AWS_SECRET_KEY