AWSTemplateFormatVersion: "2010-09-09"
Description: Full-stack mnist recognition
Resources:
  # S3 Buckets
  # ----------
  Data:
    Type: AWS::S3::Bucket,
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
  Models:
    Type: AWS::S3::Bucket,
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256